version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 2dd02_my
      MYSQL_USER: 2dd02
      MYSQL_PASSWORD: oE90kekuRj+ll0P8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
