version: '3.1'

services:

  mysql:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_USER: 2dd02
      MYSQL_PASSWORD: oE90kekuRj+ll0P8
      MYSQL_DATABASE: 2dd02_my
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql_volume:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

volumes:
  mysql_volume: