
CREATE TABLE categories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  slug VARCHAR(255) NOT NULL UNIQUE
); 

CREATE TABLE statuses (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) UNIQUE,
  slug VARCHAR(255) UNIQUE
) 

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	role VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	email_token VARCHAR(255) DEFAULT NULL,
	verified TINYINT NOT NULL DEFAULT 0,
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	token VARCHAR(32) UNIQUE,
	token_expiration DATETIME DEFAULT NULL,
	INDEX (token) 
) 

CREATE TABLE products (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,
	photo VARCHAR(255) NOT NULL,
	price DECIMAL(10, 2) NOT NULL,
	category_id INT NOT NULL,
	status_id INT NOT NULL,
	seller_id INT NOT NULL,
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (category_id) REFERENCES categories(id),
	FOREIGN KEY (status_id) REFERENCES statuses(id),
	FOREIGN KEY (seller_id) REFERENCES users(id)
) 

CREATE TABLE blocked_users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	admin_id INT NOT NULL,
	message VARCHAR(255) NOT NULL,
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) 

CREATE TABLE banned_products (
  product_id INT PRIMARY KEY AUTO_INCREMENT,
  reason VARCHAR(255) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id)
) 

CREATE TABLE orders (
	id INT AUTO_INCREMENT PRIMARY KEY,
	product_id INT,
	buyer_id INT,
	offer DECIMAL(10, 2),
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE KEY uc_product_buyer (product_id, buyer_id),
	FOREIGN KEY (product_id) REFERENCES products(id),
	FOREIGN KEY (buyer_id) REFERENCES users(id)
) 

CREATE TABLE confirmed_orders (
	order_id INT AUTO_INCREMENT PRIMARY KEY,
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (order_id) REFERENCES orders(id)
) 